"""Shell completion support for podx CLI commands.

Provides shell completion for bash, zsh, and fish shells.
"""

import click
from rich.console import Console
from rich.panel import Panel

console = Console()


def get_completion_script(shell: str) -> str:
    """Get the shell completion script for the specified shell.

    Args:
        shell: Shell type (bash, zsh, or fish)

    Returns:
        Completion script content
    """
    if shell == "bash":
        return """
# podx bash completion script
# Generated by podx --install-completion

_podx_completion() {
    local IFS=$'\\n'
    local response

    response=$(env COMP_WORDS="${COMP_WORDS[*]}" COMP_CWORD=$COMP_CWORD _PODX_COMPLETE=bash_complete $1)

    for completion in $response; do
        IFS=',' read type value <<< "$completion"

        if [[ $type == 'dir' ]]; then
            COMPREPLY=()
            compopt -o dirnames
        elif [[ $type == 'file' ]]; then
            COMPREPLY=()
            compopt -o default
        elif [[ $type == 'plain' ]]; then
            COMPREPLY+=($value)
        fi
    done

    return 0
}

_podx_completion_setup() {
    complete -o nosort -F _podx_completion podx
    complete -o nosort -F _podx_completion podx-transcribe
    complete -o nosort -F _podx_completion podx-diarize
    complete -o nosort -F _podx_completion podx-deepcast
    complete -o nosort -F _podx_completion podx-export
    complete -o nosort -F _podx_completion podx-fetch
    complete -o nosort -F _podx_completion podx-config
    complete -o nosort -F _podx_completion podx-estimate
}

_podx_completion_setup
"""
    elif shell == "zsh":
        return """
# podx zsh completion script
# Generated by podx --install-completion

#compdef podx
#compdef podx-transcribe
#compdef podx-diarize
#compdef podx-deepcast
#compdef podx-export
#compdef podx-fetch
#compdef podx-config
#compdef podx-estimate

_podx_completion() {
    local -a completions
    local -a completions_with_descriptions
    local -a response
    (( ! $+commands[podx] )) && return 1

    response=("${(@f)$(env COMP_WORDS="${words[*]}" COMP_CWORD=$((CURRENT-1)) _PODX_COMPLETE=zsh_complete podx)}")

    for type key descr in ${response}; do
        if [[ "$type" == "plain" ]]; then
            if [[ "$descr" == "_" ]]; then
                completions+=("$key")
            else
                completions_with_descriptions+=("$key":"$descr")
            fi
        elif [[ "$type" == "dir" ]]; then
            _path_files -/
        elif [[ "$type" == "file" ]]; then
            _path_files -f
        fi
    done

    if [ -n "$completions_with_descriptions" ]; then
        _describe -V unsorted completions_with_descriptions -U
    fi

    if [ -n "$completions" ]; then
        compadd -U -V unsorted -a completions
    fi
}

compdef _podx_completion podx
compdef _podx_completion podx-transcribe
compdef _podx_completion podx-diarize
compdef _podx_completion podx-deepcast
compdef _podx_completion podx-export
compdef _podx_completion podx-fetch
compdef _podx_completion podx-config
compdef _podx_completion podx-estimate
"""
    elif shell == "fish":
        return """
# podx fish completion script
# Generated by podx --install-completion

function _podx_completion
    set -l response (env _PODX_COMPLETE=fish_complete COMP_WORDS=(commandline -opc) COMP_CWORD=(commandline -t) podx)

    for completion in $response
        set -l metadata (string split "," $completion)

        if test $metadata[1] = "dir"
            __fish_complete_directories $metadata[2]
        else if test $metadata[1] = "file"
            __fish_complete_path $metadata[2]
        else if test $metadata[1] = "plain"
            echo $metadata[2]
        end
    end
end

complete --no-files --command podx --arguments "(_podx_completion)"
complete --no-files --command podx-transcribe --arguments "(_podx_completion)"
complete --no-files --command podx-diarize --arguments "(_podx_completion)"
complete --no-files --command podx-deepcast --arguments "(_podx_completion)"
complete --no-files --command podx-export --arguments "(_podx_completion)"
complete --no-files --command podx-fetch --arguments "(_podx_completion)"
complete --no-files --command podx-config --arguments "(_podx_completion)"
complete --no-files --command podx-estimate --arguments "(_podx_completion)"
"""
    else:
        raise ValueError(f"Unsupported shell: {shell}")


def install_completion(shell: str) -> str:
    """Install shell completion for the specified shell.

    Args:
        shell: Shell type (bash, zsh, or fish)

    Returns:
        Installation instructions
    """
    # Get script to validate shell is supported
    _ = get_completion_script(shell)

    if shell == "bash":
        completion_file = "~/.bash_completion.d/podx.sh"
        source_line = f"source {completion_file}"
        rc_file = "~/.bashrc"

        instructions = f"""
[bold green]Bash Completion Installation:[/bold green]

1. Create completion directory:
   [cyan]mkdir -p ~/.bash_completion.d[/cyan]

2. Save the completion script:
   [cyan]podx --install-completion bash > {completion_file}[/cyan]

3. Add to your {rc_file}:
   [cyan]echo '{source_line}' >> {rc_file}[/cyan]

4. Reload your shell:
   [cyan]source {rc_file}[/cyan]

Now you can use TAB completion with podx commands!
"""

    elif shell == "zsh":
        completion_file = "~/.zsh/completion/_podx"
        rc_file = "~/.zshrc"

        instructions = f"""
[bold green]Zsh Completion Installation:[/bold green]

1. Create completion directory:
   [cyan]mkdir -p ~/.zsh/completion[/cyan]

2. Save the completion script:
   [cyan]podx --install-completion zsh > {completion_file}[/cyan]

3. Add to your {rc_file} (before compinit):
   [cyan]fpath=(~/.zsh/completion $fpath)[/cyan]
   [cyan]autoload -Uz compinit && compinit[/cyan]

4. Reload your shell:
   [cyan]source {rc_file}[/cyan]

Now you can use TAB completion with podx commands!
"""

    elif shell == "fish":
        completion_file = "~/.config/fish/completions/podx.fish"

        instructions = f"""
[bold green]Fish Completion Installation:[/bold green]

1. Create completion directory:
   [cyan]mkdir -p ~/.config/fish/completions[/cyan]

2. Save the completion script:
   [cyan]podx --install-completion fish > {completion_file}[/cyan]

3. Reload fish:
   [cyan]exec fish[/cyan]

Now you can use TAB completion with podx commands!
"""

    else:
        raise ValueError(f"Unsupported shell: {shell}")

    return instructions


@click.command(help="Install shell completion")
@click.argument(
    "shell",
    type=click.Choice(["bash", "zsh", "fish"], case_sensitive=False),
    required=False,
)
@click.option(
    "--show-script",
    is_flag=True,
    help="Show completion script instead of instructions",
)
def main(shell: str, show_script: bool):
    """Install shell completion for podx commands.

    Examples:
        podx-completion bash
        podx-completion zsh
        podx-completion fish
        podx-completion bash --show-script > ~/.bash_completion.d/podx.sh
    """
    # Auto-detect shell if not provided
    if not shell:
        import os

        shell_env = os.environ.get("SHELL", "")
        if "bash" in shell_env:
            shell = "bash"
        elif "zsh" in shell_env:
            shell = "zsh"
        elif "fish" in shell_env:
            shell = "fish"
        else:
            console.print(
                "[red]Error:[/red] Could not auto-detect shell. "
                "Please specify: bash, zsh, or fish"
            )
            return

        console.print(f"[dim]Auto-detected shell: {shell}[/dim]\n")

    shell = shell.lower()

    if show_script:
        # Output the script directly (for piping to file)
        script = get_completion_script(shell)
        print(script)
    else:
        # Show installation instructions
        instructions = install_completion(shell)
        console.print(Panel(instructions, title=f"Shell Completion - {shell.upper()}"))


if __name__ == "__main__":
    main()
